version: "2"
run:
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
  sort-order:
    - file
    - linter
    - severity
linters:
  enable:
    - bodyclose
    - dupl
    - goprintffuncname
    - misspell
    - nakedret
    - prealloc
    - unparam
    - whitespace
  disable:
    - dogsled
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - ineffassign
    - lll
    - staticcheck
    - unconvert
    - unused
  settings:
    gocyclo:
      min-complexity: 10
    unused:
      exported-fields-are-used: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: info
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
