#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# shellcheck source=/dev/null
source "$SCRIPT_DIR"/argconverter.sh

modified_args=$(arg_conversion "$@")

"$SCRIPT_DIR"/scicat-cli datasetPublishData "${modified_args[@]}"
