Scicat:
  Host: http://scicat:8080/api/v3
  AccessToken: "asdf"
Transfer:
  Method: S3
  S3:
    Endpoint: s3-endpoint:9000
    Bucket: landingzone
    Checksum: true
  Globus:
    Endpoint: globus.psi.ch
Misc:
  ConcurrencyLimit: 2