// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {uuid} from '../models';

export function CancelTask(arg1:string):Promise<void>;

export function RemoveTask(arg1:string):Promise<void>;

export function ScheduleTask(arg1:uuid.UUID):Promise<void>;

export function SelectFolder():Promise<void>;
